#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Travelr.Resource", IsApplication=true)]

namespace Travelr
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Travelr.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Travelr.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AccountInfo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backarrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backarrowTransparent = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Belgie = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BelgieInfo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_landen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bgHomepage = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bglandinfo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_europa_delen = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_verder = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btnBackGroot = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btnHome = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btnSearch = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Bulgarije = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int BulgarijeInfo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ButtonLoginStyle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Denemarken = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int DenemarkenInfo = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Duitsland = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int DuitslandInfo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int edit_text_style = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Finland = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int FinlandInfo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Frankrijk = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int FrankrijkInfo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Griekenland = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int GriekenlandInfo = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_email2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon_red_alert = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int icon_username2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int icon_wachtwoord2 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Ierland = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int IerlandInfo = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Ijsland = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int IjslandInfo = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int imgBezienswaardigheid = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int imgGerechten = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int imgHoofdstad = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int imgHotel = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int imgNatuurgebied = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int imgStreep = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int imgValuta = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Italie = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ItalieInfo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Kroatie = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int KroatieInfo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Nederland = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int NederlandInfo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Noorwegen = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int NoorwegenInfo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Oekraine = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int OekraineInfo = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Oostenrijk = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int OostenrijkInfo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Polen = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int PolenInfo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Portugal = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int PortugalInfo = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ratingbar = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ratingbar_empty = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ratingbar_filled = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ratingbar_staroff = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ratingbar_staron = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int recensie = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int reg_achtergrond1 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int rounded_corner = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Rusland = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int RuslandInfo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Slovenie = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int SlovenieInfo = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Slowakije = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int SlowakijeInfo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Spanje = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int SpanjeInfo = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int TravelrIcon = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Tsjechie = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int TsjechieInfo = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Zweden = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ZwedenInfo = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int Zwitserland = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ZwitserlandInfo = 2130837585;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070070
			public const int btnAccount = 2131165296;
			
			// aapt resource value: 0x7f070068
			public const int btnAddFavorieten = 2131165288;
			
			// aapt resource value: 0x7f070039
			public const int btnBack = 2131165241;
			
			// aapt resource value: 0x7f070001
			public const int btnBackLI = 2131165185;
			
			// aapt resource value: 0x7f07007d
			public const int btnBevestig = 2131165309;
			
			// aapt resource value: 0x7f070012
			public const int btnFavo1 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int btnFavo2 = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int btnFavo3 = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int btnFavo4 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int btnFavo5 = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int btnFavo6 = 2131165212;
			
			// aapt resource value: 0x7f07004a
			public const int btnHome = 2131165258;
			
			// aapt resource value: 0x7f07003d
			public const int btnLandKeuze1 = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int btnLandKeuze2 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int btnLandKeuze3 = 2131165247;
			
			// aapt resource value: 0x7f070043
			public const int btnLandKeuze4 = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int btnLandKeuze5 = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int btnLandKeuze6 = 2131165253;
			
			// aapt resource value: 0x7f07006c
			public const int btnLogin = 2131165292;
			
			// aapt resource value: 0x7f07006f
			public const int btnLoginLogout = 2131165295;
			
			// aapt resource value: 0x7f070072
			public const int btnNoordEuropa = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int btnOostEuropa = 2131165299;
			
			// aapt resource value: 0x7f070049
			public const int btnRecensie = 2131165257;
			
			// aapt resource value: 0x7f070077
			public const int btnRecensieBack = 2131165303;
			
			// aapt resource value: 0x7f070078
			public const int btnRecensieHome = 2131165304;
			
			// aapt resource value: 0x7f0700b0
			public const int btnRegistreerd = 2131165360;
			
			// aapt resource value: 0x7f07006d
			public const int btnSkipLogin = 2131165293;
			
			// aapt resource value: 0x7f07000f
			public const int btnVeranderwachtwoord = 2131165199;
			
			// aapt resource value: 0x7f070075
			public const int btnWestEuropa = 2131165301;
			
			// aapt resource value: 0x7f0700b4
			public const int btnZoekBack = 2131165364;
			
			// aapt resource value: 0x7f070071
			public const int btnZoekLand = 2131165297;
			
			// aapt resource value: 0x7f070074
			public const int btnZuidEuropa = 2131165300;
			
			// aapt resource value: 0x7f07006b
			public const int btnregistreer = 2131165291;
			
			// aapt resource value: 0x7f070020
			public const int button_cancel = 2131165216;
			
			// aapt resource value: 0x7f070009
			public const int imageView1 = 2131165193;
			
			// aapt resource value: 0x7f070050
			public const int imageView2 = 2131165264;
			
			// aapt resource value: 0x7f070055
			public const int imageView3 = 2131165269;
			
			// aapt resource value: 0x7f07005c
			public const int imageView4 = 2131165276;
			
			// aapt resource value: 0x7f07004f
			public const int imageView5 = 2131165263;
			
			// aapt resource value: 0x7f07001e
			public const int imageview_icon = 2131165214;
			
			// aapt resource value: 0x7f070061
			public const int imgHotel = 2131165281;
			
			// aapt resource value: 0x7f070025
			public const int imgHulpAccount = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int imgHulpBack = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int imgHulpHome = 2131165225;
			
			// aapt resource value: 0x7f070022
			public const int imgHulpLogo = 2131165218;
			
			// aapt resource value: 0x7f070033
			public const int imgHulpNederland = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int imgHulpzoek = 2131165238;
			
			// aapt resource value: 0x7f07004b
			public const int imgLand = 2131165259;
			
			// aapt resource value: 0x7f070065
			public const int imgValuta = 2131165285;
			
			// aapt resource value: 0x7f07002f
			public const int imghulpRecensie = 2131165231;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout3 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout4 = 2131165195;
			
			// aapt resource value: 0x7f070028
			public const int linearLayout5 = 2131165224;
			
			// aapt resource value: 0x7f070032
			public const int linearLayout8 = 2131165234;
			
			// aapt resource value: 0x7f0700b3
			public const int lv = 2131165363;
			
			// aapt resource value: 0x7f070081
			public const int rbR1 = 2131165313;
			
			// aapt resource value: 0x7f07009c
			public const int rbR10 = 2131165340;
			
			// aapt resource value: 0x7f07009f
			public const int rbR11 = 2131165343;
			
			// aapt resource value: 0x7f0700a2
			public const int rbR12 = 2131165346;
			
			// aapt resource value: 0x7f0700a5
			public const int rbR13 = 2131165349;
			
			// aapt resource value: 0x7f0700a8
			public const int rbR14 = 2131165352;
			
			// aapt resource value: 0x7f0700ab
			public const int rbR15 = 2131165355;
			
			// aapt resource value: 0x7f070084
			public const int rbR2 = 2131165316;
			
			// aapt resource value: 0x7f070087
			public const int rbR3 = 2131165319;
			
			// aapt resource value: 0x7f07008a
			public const int rbR4 = 2131165322;
			
			// aapt resource value: 0x7f07008d
			public const int rbR5 = 2131165325;
			
			// aapt resource value: 0x7f070090
			public const int rbR6 = 2131165328;
			
			// aapt resource value: 0x7f070093
			public const int rbR7 = 2131165331;
			
			// aapt resource value: 0x7f070096
			public const int rbR8 = 2131165334;
			
			// aapt resource value: 0x7f070099
			public const int rbR9 = 2131165337;
			
			// aapt resource value: 0x7f07007b
			public const int rbRecensie = 2131165307;
			
			// aapt resource value: 0x7f07000a
			public const int scrollView1 = 2131165194;
			
			// aapt resource value: 0x7f0700b2
			public const int sv = 2131165362;
			
			// aapt resource value: 0x7f070010
			public const int textView1 = 2131165200;
			
			// aapt resource value: 0x7f070079
			public const int textView4 = 2131165305;
			
			// aapt resource value: 0x7f07007e
			public const int textView5 = 2131165310;
			
			// aapt resource value: 0x7f07001f
			public const int textview_message = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int textview_title = 2131165213;
			
			// aapt resource value: 0x7f07003c
			public const int txtAantalLanden = 2131165244;
			
			// aapt resource value: 0x7f070057
			public const int txtBezienswaardigheid1 = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int txtBezienswaardigheid2 = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int txtBezienswaardigheid3 = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int txtBezienswaardigheid4 = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int txtBezienswaardigheid5 = 2131165275;
			
			// aapt resource value: 0x7f070056
			public const int txtBezienswaardigheidTitel = 2131165270;
			
			// aapt resource value: 0x7f0700ae
			public const int txtEmail = 2131165358;
			
			// aapt resource value: 0x7f07003b
			public const int txtEuropaDeel = 2131165243;
			
			// aapt resource value: 0x7f070011
			public const int txtFavo1 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int txtFavo2 = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int txtFavo3 = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int txtFavo4 = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int txtFavo5 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int txtFavo6 = 2131165211;
			
			// aapt resource value: 0x7f0700ad
			public const int txtFirstName = 2131165357;
			
			// aapt resource value: 0x7f070069
			public const int txtFirstName_login = 2131165289;
			
			// aapt resource value: 0x7f07007f
			public const int txtGeenRecensie = 2131165311;
			
			// aapt resource value: 0x7f070052
			public const int txtGerecht1 = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int txtGerecht2 = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int txtGerecht3 = 2131165268;
			
			// aapt resource value: 0x7f070051
			public const int txtGerechtTitel = 2131165265;
			
			// aapt resource value: 0x7f070021
			public const int txtHelpPagina = 2131165217;
			
			// aapt resource value: 0x7f07004e
			public const int txtHoofdstad = 2131165262;
			
			// aapt resource value: 0x7f07004d
			public const int txtHoofdstadTitel = 2131165261;
			
			// aapt resource value: 0x7f070063
			public const int txtHotel1 = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int txtHotel2 = 2131165284;
			
			// aapt resource value: 0x7f070062
			public const int txtHotelTitel = 2131165282;
			
			// aapt resource value: 0x7f070023
			public const int txtHulpContact = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int txtHulpContactInfo = 2131165220;
			
			// aapt resource value: 0x7f07002a
			public const int txtHulpHome = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int txtHulpHomeInfo = 2131165227;
			
			// aapt resource value: 0x7f070030
			public const int txtHulpRecensie = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int txtHulpRecensieInfo = 2131165233;
			
			// aapt resource value: 0x7f07002d
			public const int txtHulpTerug = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int txtHulpTerugInfo = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int txtHulpZoeken = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int txtHulpZoekenInfo = 2131165240;
			
			// aapt resource value: 0x7f070026
			public const int txtHulppass = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int txtHulppassinfo = 2131165223;
			
			// aapt resource value: 0x7f070040
			public const int txtLandKeuze1 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int txtLandKeuze2 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int txtLandKeuze3 = 2131165250;
			
			// aapt resource value: 0x7f070046
			public const int txtLandKeuze4 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int txtLandKeuze5 = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int txtLandKeuze6 = 2131165256;
			
			// aapt resource value: 0x7f070002
			public const int txtLandNaam = 2131165186;
			
			// aapt resource value: 0x7f07004c
			public const int txtLandVerhaal = 2131165260;
			
			// aapt resource value: 0x7f070080
			public const int txtNaamR1 = 2131165312;
			
			// aapt resource value: 0x7f07009b
			public const int txtNaamR10 = 2131165339;
			
			// aapt resource value: 0x7f07009e
			public const int txtNaamR11 = 2131165342;
			
			// aapt resource value: 0x7f0700a1
			public const int txtNaamR12 = 2131165345;
			
			// aapt resource value: 0x7f0700a4
			public const int txtNaamR13 = 2131165348;
			
			// aapt resource value: 0x7f0700a7
			public const int txtNaamR14 = 2131165351;
			
			// aapt resource value: 0x7f0700aa
			public const int txtNaamR15 = 2131165354;
			
			// aapt resource value: 0x7f070083
			public const int txtNaamR2 = 2131165315;
			
			// aapt resource value: 0x7f070086
			public const int txtNaamR3 = 2131165318;
			
			// aapt resource value: 0x7f070089
			public const int txtNaamR4 = 2131165321;
			
			// aapt resource value: 0x7f07008c
			public const int txtNaamR5 = 2131165324;
			
			// aapt resource value: 0x7f07008f
			public const int txtNaamR6 = 2131165327;
			
			// aapt resource value: 0x7f070092
			public const int txtNaamR7 = 2131165330;
			
			// aapt resource value: 0x7f070095
			public const int txtNaamR8 = 2131165333;
			
			// aapt resource value: 0x7f070098
			public const int txtNaamR9 = 2131165336;
			
			// aapt resource value: 0x7f07005e
			public const int txtNatuurgebied1 = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int txtNatuurgebied2 = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int txtNatuurgebied3 = 2131165280;
			
			// aapt resource value: 0x7f07005d
			public const int txtNatuurgebiedenTitel = 2131165277;
			
			// aapt resource value: 0x7f0700af
			public const int txtPassword = 2131165359;
			
			// aapt resource value: 0x7f07006a
			public const int txtPassword_login = 2131165290;
			
			// aapt resource value: 0x7f07007a
			public const int txtRGebruikersNaam = 2131165306;
			
			// aapt resource value: 0x7f07007c
			public const int txtRecensie = 2131165308;
			
			// aapt resource value: 0x7f07006e
			public const int txtSendHelp = 2131165294;
			
			// aapt resource value: 0x7f070076
			public const int txtSendHelp2 = 2131165302;
			
			// aapt resource value: 0x7f0700b1
			public const int txtSignUpTitle = 2131165361;
			
			// aapt resource value: 0x7f070082
			public const int txtTextR1 = 2131165314;
			
			// aapt resource value: 0x7f07009d
			public const int txtTextR10 = 2131165341;
			
			// aapt resource value: 0x7f0700a0
			public const int txtTextR11 = 2131165344;
			
			// aapt resource value: 0x7f0700a3
			public const int txtTextR12 = 2131165347;
			
			// aapt resource value: 0x7f0700a6
			public const int txtTextR13 = 2131165350;
			
			// aapt resource value: 0x7f0700a9
			public const int txtTextR14 = 2131165353;
			
			// aapt resource value: 0x7f0700ac
			public const int txtTextR15 = 2131165356;
			
			// aapt resource value: 0x7f070085
			public const int txtTextR2 = 2131165317;
			
			// aapt resource value: 0x7f070088
			public const int txtTextR3 = 2131165320;
			
			// aapt resource value: 0x7f07008b
			public const int txtTextR4 = 2131165323;
			
			// aapt resource value: 0x7f07008e
			public const int txtTextR5 = 2131165326;
			
			// aapt resource value: 0x7f070091
			public const int txtTextR6 = 2131165329;
			
			// aapt resource value: 0x7f070094
			public const int txtTextR7 = 2131165332;
			
			// aapt resource value: 0x7f070097
			public const int txtTextR8 = 2131165335;
			
			// aapt resource value: 0x7f07009a
			public const int txtTextR9 = 2131165338;
			
			// aapt resource value: 0x7f07003a
			public const int txtTitle = 2131165242;
			
			// aapt resource value: 0x7f070007
			public const int txtUserID = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int txtUsername = 2131165188;
			
			// aapt resource value: 0x7f070067
			public const int txtValuta = 2131165287;
			
			// aapt resource value: 0x7f070066
			public const int txtValutaTitel = 2131165286;
			
			// aapt resource value: 0x7f07000c
			public const int txtWachtwoord = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int txtgetUserID = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int txtgetUsername = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int txtgetnewpass = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int txtgetoldpass = 2131165197;
			
			// aapt resource value: 0x7f070034
			public const int txthulpinformatie = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int txthulplandinfo = 2131165237;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Help = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Landen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LandInfo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Recensie = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Registreer = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ZoekLand = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int DBLandInformatie2 = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomRatingBar = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
